
CREATE TABLE CUSTOMERS
(CUSTOMER_NUM CHAR(3) PRIMARY KEY,
ACCOUNT_ID CHAR(3) FOREIGN KEY,
LAST_NAME CHAR(35) NOT NULL,
FIRST_NAME CHAR(35)
STREET CHAR(15),
CITY CHAR(15),
STATE CHAR(2),
ZIP CHAR(5) );




CREATE TABLE EMPLOYEES
(EMPLOYEE_ID CHAR(3) PRIMARY KEY,
CUSTOMER_NUM CHAR(3) FOREIGN KEY,
DELIVERY_ID CHAR FOREIGN KEY,
FIRST_NAME CHAR(35) NOT NULL,
LAST_NAME CHAR(35),
STREET CHAR(15),
CITY CHAR(15),
STATE CHAR(2),
ZIP CHAR(5), 
CELLPHONE NUMBER.
START_DATE DATE,
END_DATE DATE);


CREATE TABLE ORDERS
(ORDER_ID CHAR(3) PRIMARY KEY,
PRODUCT_ID CHAR FOREIGN KEY,
NUMBER_OF_ORDERS NUMBER,
DATE_ORDERED  DATE, 
DATE_DELIVERED DATE );


CREATE TABLE PRODUCTS 
(PRODUCT_ID CHAR(3) PRIMARY KEY,
PRODUCT_NAME CHAR,
ON_HAND CHAR, 
AMOUNT_SOLD NUMBER,
COST NUMBER,
DESCRIPTION CHAR );


CREATE TABLE DELIVERIES
(DILVERY_NUM CHAR(3) PRIMARY KEY,
DATE  DATE,
TIME  TIME, 
NUM_OF_ITEMS NUMBER );



CREATE TABLE SUPPLIERS 
(SUPPLIER_ID CHAR(3) PRIMARY KEY,
NAME CHAR,
CELLPHONE NUMBER, 
EMAIL CHAR,
DELIVERY_TIME DATE/TIME,
COST NUMBER );



CREATE TABLE STORE
(STORE_ID CHAR(3) PRIMARY KEY,
REVENUE NUMBER ,
ADDRESS CHAR,
CITY CHAR,
STATE CHAR,
ZIPCODE NUMBER,
PHONE NUMBER,
MANAGER CHAR );



CREATE TABLE INVENTORY
(INVENTORY_NUM CHAR PRIMARY,
ITEMS_SOLD NUMBER,
ITEMS_LEFT NUMBER,
ITEMS_NEEDED NUMBER );



CREATE TABLE PAYMENT_INFO
(PAYMENT_ID CHAR(3) PRIMARY KEY,
LAST_NAME CHAR ,
FIRST_NAME CHAR,
CREDIT_CARD_NUM NUMBER,
EXPIRATION_DATE DATE/TIME,
PIN NUMBER);



CREATE TABLE ACCOUNT_INFO
(ACCOUNT_ID CHAR(3) PRIMARY KEY,
USERNAME CHAR ,
PASSWORD CHAR,
EMAIL CHAR);







